CREATE TABLE Person (
    person_id VARCHAR(15) PRIMARY KEY,  
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    date_of_birth DATE
);

CREATE TABLE Resident (
    resident_id INT PRIMARY KEY,      
    person_id VARCHAR(15) UNIQUE,       
    apartment VARCHAR(20),
    phone VARCHAR(20),
    registered_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_resident_person FOREIGN KEY (person_id)
        REFERENCES Person(person_id)
);

CREATE TABLE ParkingSpot (
    spot_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    code VARCHAR2(20) UNIQUE NOT NULL,  
    type VARCHAR2(10) CHECK (type IN ('CAR', 'MOTORBIKE')),
    status VARCHAR2(20) CHECK (status IN ('FREE', 'ASSIGNED', 'OCCUPIED', 'OUT_OF_SERVICE')),
    assigned_resident_id INT,            
    version NUMBER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_assigned_resident FOREIGN KEY (assigned_resident_id)
        REFERENCES Resident(resident_id)
);

CREATE TABLE SpotHistory (
    history_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    parking_spot_id NUMBER NOT NULL,    
    person_id VARCHAR(15) NOT NULL,   
    change_type VARCHAR2(50),           
    changed_by VARCHAR2(100),          
    change_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_history_spot FOREIGN KEY (parking_spot_id)
        REFERENCES ParkingSpot(spot_id),
    CONSTRAINT fk_history_person FOREIGN KEY (person_id)
        REFERENCES Person(person_id)
);

